name: test_db

services:
  db:
    image: pgvector/pgvector:pg17-bookworm
    container_name: pgvector_db
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # shm_size removed; defaults to 64MB
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: simple_agent
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pgdata:


