name: agents_db

services:
  db:
    image: pgvector/pgvector:pg18 #Updated image to use vector db extensions
    container_name: agents_db
    restart: always
    environment:
      - POSTGRES_DB=agents
      - POSTGRES_USER=agents
      - POSTGRES_PASSWORD=agents
    ports:
      - "5432:5432"
    #Need to make changes to volume path for pg18 
    volumes:
      - agents_db:/var/lib/postgresql

volumes:
  agents_db:


